### PR TITLE
Fixes Issue #40

### LINKED ISSUE #40: Minor bug rendering Site Title when containing HTML entities
### Description

If the WordPress Site Title contains any entity character, like **apostrophe** or **&**, it haves problems of "double" codification at **Nav component** and at **title tag**.

### Screenshots

|Bug                    |
| ---------------------------------- |
| apostrophe-encode|

### PR DESCRIPTION
**Pull request by GuilleAngulo**
### Description

When retrieving data from WordPress REST API is checked if the site title contains any HTML special character, and if is 
the case it replaces by its Unicode version. I found relevant to check: [ ' | " | & ], as it can appear in a site title. 

Reference: https://dev.w3.org/html5/html-author/charref

### Screenshots

|Before                   | After
| ---------------------------------- | ---------------------------------- |
| before| after |

Fixes #40

### CODE REVIEW

**Comment by GuilleAngulo** [comment]
Oops, just saw you already made a pull request for fixing it @colbyfayock

**Comment by colbyfayock** [comment]
ah yeah i think we're good rendering the title there unless you think that isn't a good idea!

**Comment by GuilleAngulo** [comment]
Yeah, just checked and the problem is solved for the Nav render, but it stills gets the special characters at title tag at tab (like the 'before' screenshot). I though in another solution in my suggestion, where right when getSiteMetadata() is called the title is 'sanitized' by replacing that characters by unicode. What do you think?

File: src/lib/site.js [hunk 1]
```diff
@@ -17,5 +17,22 @@ export async function getSiteMetadata() {
...
+
+  let decoded = text;
+
+  const entities = {
+    '&amp;': '\u0026',
+    '&quot;': '\u0022',
+    '&#039;': '\u0027',
+  };
+
+  return decoded.replace(/&amp;|&quot;|&#039;/g, (char) => entities[char]);
```
Comment (colbyfayock) [inline src/lib/site.js:37]: didn't realize you could pass in a function like that, nice!

**Comment by colbyfayock** [comment]
ah right - good call. yeah i think that works well then

thanks for making the change

**Comment by GuilleAngulo** [comment]
Thanks, great project 🎉 !
