### PR TITLE
Search Index Compiler Run Check

### LINKED ISSUE #37: Build / Deploy fails due to empty wp-search.json
Noticed this happen at least two times now, it seems like during the build, the wp-search.json file ends up empty and ends up failing due to it

I haven't been able to reproduce locally yet

image

### PR DESCRIPTION
**Pull request by colbyfayock**
I noticed when adding some logging to debug #37 that this plugin runs a billion times. This is an attempt to reduce it down to 1 time for production builds.

We're using the `run` and `watchRun` hooks again for webpack. The reason being I'm able to find an options object in both instances where I can check if we're on the `main` compilation and only run this process once when we see that

This is resulting in a single run for production build 🙌 

This still runs multiple times during development builds but I think that's okay. It'll run every time a change is made and recompiled.

I'm not sure if this actually fixes the issue related to #37, but I'm going to mark it as such and we can loop back if it pops back up as it should be much easier to debug with the logging i added and the fact it will only run once on build.

Fixes #37

### CODE REVIEW

**Comment by colbyfayock** [comment]
@doingandlearning mind giving a pair of eyes on this?

File: plugins/search-index-compiler.js [hunk 1]
```diff
@@ -59,7 +66,22 @@ class SearchIndexWebpackPlugin {
...
+    // We want this plugin to be able to run both during development mode and production
+    // mode, but we also only want it to compile once. We need a way to be able to detect
+    // some kind of identifier that will only be available once, where here we're using
+    // the `main` entry. When these are ran, we check if that's in the active compiler
+    // options and only run if it is
+
+    compiler.hooks.run.tap(PLUGIN_NAME, async (compiler) => {
+      if (!compiler.options.entry.main) return;
+      await this.index(compiler, this.options);
+    });
```
Comment (doingandlearning) [inline plugins/search-index-compiler.js:78]: When I run this in production, it only runs once as expected!

**Review by doingandlearning — APPROVED** [review]
Woohoo! Great :)
